
llibre_get:
    path: /llibres/{llibreId}
    controller: rubenrubiob\Infrastructure\Ui\Http\Controller\GetLlibreController
    methods: [GET]

llibres_find:
    path: /llibres
    controller: rubenrubiob\Infrastructure\Ui\Http\Controller\FindLlibresController
    methods: [GET]
