#index:
#    path: /
#    controller: App\Controller\DefaultController::index
llibre_get:
    path: /llibre/{llibreId}
    controller: rubenrubiob\Infrastructure\Ui\Http\Controller\GetLlibreController
    methods: [GET]
