name: CI/CD blog-src

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  composer-install:
      runs-on: ubuntu-latest
      steps:
        - name: Code checkout
          uses: actions/checkout@v3
        - name: Setup
          uses: ./.github/actions/setup/
        # Cleanup
        - name: Move cache
          run: |
            rm -rf /tmp/docker-cache
            mv /tmp/docker-cache-new /tmp/docker-cache
        - name: Make composer install
          run: make composer-install
  test:
    runs-on: ubuntu-latest
    needs: [composer-install]
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup/
      - name: Run Unit Tests
        run: make unit-test
      - name: Run Functional Tests
        run: make functional-test
      - name: Run Mutation Testing
        run: make infection

  static-analysis:
    runs-on: ubuntu-latest
    needs: [composer-install]
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup/
      - name: PHPStan
        run: make phpstan
      - name: Run Psalm
        run: make psalm

  architecture-checks:
    runs-on: ubuntu-latest
    needs: [composer-install]
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup/
      - name: Deptrac Hexagonal Architecture Layers
        run: make architecture-hexagonal-layers

  composer-checks:
    runs-on: ubuntu-latest
    needs: [composer-install]
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup/
      - name: Composer Validate
        run: make composer-validate
      - name: Composer Require Checker
        run: make composer-require-checker
      - name: Composer Unused
        run: make composer-unused

  symfony-checks:
    runs-on: ubuntu-latest
    needs: [composer-install]
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup/
      - name: Lint Container
        run: make symfony-lint-container
      - name: Lint Yaml
        run: make symfony-lint-yaml
