name: CI/CD blog-src

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  composer-install:
      runs-on: ubuntu-latest
      steps:
        - name: Code checkout
          uses: actions/checkout@v3
        - name: Setup
          uses: ./.github/actions/setup/
        # Cleanup
        - name: Move cache
          run: |
            rm -rf /tmp/docker-cache
            mv /tmp/docker-cache-new /tmp/docker-cache
        - name: Make composer install
          run: make composer-install
  test:
    runs-on: ubuntu-latest
    needs: [composer-install]
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup/
      # Tests
      - name: Run Unit Tests
        run: make unit-test
      - name: Run Functional Tests
        run: make functional-test
      - name: PHPStan
        run: make phpstan
      - name: Run Psalm
        run: make psalm
      - name: Run infection
        run: make infection
  quality:
    runs-on: ubuntu-latest
    needs: [composer-install]
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup/
      # Tests
      - name: PHPStan
        run: make phpstan
      - name: Run Psalm
        run: make psalm
      - name: Run infection
        run: make infection
