name: CI/CD blog-src

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  setup:
      runs-on: ubuntu-latest
      steps:
        - name: Setup
          uses: ./.github/actions/action-setup.yaml
        # Cleanup
        - name: Move cache
          run: |
            rm -rf /tmp/docker-cache
            mv /tmp/docker-cache-new /tmp/docker-cache
  test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Setup
        uses: ./.github/actions/action-setup.yaml
      # Tests
      - name: Run Unit Tests
        run: make unit-test
      - name: Run Functional Tests
        run: make functional-test
      - name: PHPStan
        run: make phpstan
      - name: Run Psalm
        run: make psalm
      - name: Run infection
        run: make infection
  quality:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Setup
        uses: ./.github/actions/action-setup.yaml
      # Tests
      - name: PHPStan
        run: make phpstan
      - name: Run Psalm
        run: make psalm
      - name: Run infection
        run: make infection
